name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Validate composer.json and composer.lock
        run: composer validate
  
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
  
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest
  
      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
  
      # - name: Run test suite
      #   run: composer run-script test

      # https://github.com/marketplace/actions/php-lint
      - name: PHP Lint
        uses: michaelw90/PHP-Lint@2.1.0

      # https://github.com/marketplace/actions/image-actions
      - name: Image Actions
        # You may pin to the exact commit or the version.
        # uses: calibreapp/image-actions@737ceeaeed61e17b8d358358a303f1b8d177b779
        uses: calibreapp/image-actions@1.1.0
        with:
          # GitHub Token
          githubToken: 
          # JPEG quality level
          jpegQuality: # optional, default is 80
          # PNG quality level
          pngQuality: # optional, default is 80
          # WEBP quality level
          webpQuality: # optional, default is 80
          # Paths to ignore during search
          ignorePaths: # optional, default is node_modules/**
