name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Validate composer.json and composer.lock
        run: composer validate
  
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
  
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest
  
      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
  
      # - name: Run test suite
      #   run: composer run-script test

      # https://github.com/OskarStark/php-cs-fixer-ga
      - name: OSKAR-PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@2.16.7

      # https://github.com/phonito/phonito-scanner-action
      - name: Docker Vulnerability Scan With Phonito Security
        uses: phonito/phonito-scanner-action@v1.1.0
